### ISSUE TITLE
fine-tuning demo

### ISSUE THREAD

**Issue by Geniukx** [BatFaceWayne/POV_Surgery#1]
Appreciate for your excellent job! When will the complete fine-tuning demo code be released?

**Comment by Geniukx** [comment]
Oh, sorry. I just saw that there is only Introduction in README.md, and I thought the demo has not been uploaded yet. But can you guys add a little more detailed instructions about the finetune pipeline? I would greatly appreciate it if possible!

**Comment by BatFaceWayne** [comment]
Hi, you could refer to the original HandOccNet repo for instructions: https://github.com/namepllet/HandOccNet. The major difference is we switched to a customized dataloader. Let me know if you have further questions.
