### ISSUE TITLE
Question about annotations + coordinate system

### ISSUE THREAD

**Issue by cgsaxner** [BatFaceWayne/POV_Surgery#2]
Hi, thank you for the great dataset & project!

I was looking through the annotations and was wondering if you could explain more about what the individual keys mean? "CamR" and "CamT" are quite straightforward, but what exactly is "grab2world" and "base object R" and how would I need to combine them to visualize the relation between camera and hand in e.g. Open3D? 
Also, what coordinate system are the annotations in (y-up, z-up, left-handed, right-handed...)?

Thank you!

**Comment by BatFaceWayne** [comment]
Hi, thanks for the interest in our work! You could refer to the colab notebook here: https://colab.research.google.com/drive/1gX2Vg0dBb0xqzl5vIipwOPV5HarlOlYn?usp=sharing
or the reprojection scripts under "vis_data" for reference. We have prepared the reprojection script for pyrender and opencv. You should get open3d visualization quite easily following pyrender script.

base object R is just a rotation used in preprocessing of GrabNet, this is set to a constant for a specific object sequence.  "grab2world" is the global transformation from the generated Canonical Hand-Object grasping pose to align with body motion. (From left to right in the image below): 
<img width="501" alt="Screenshot 2023-12-13 at 16 14 59" src="https://github.com/BatFaceWayne/POV_Surgery/assets/44198563/fd0787e0-63d4-47b7-80b3-201fdd293c8c">

Thanks for the comment and I would update this info in the readme afterwards :)
